name: to_walk_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  google_nav_bar: ^5.0.6
  health: ^10.2.0
  permission_handler: ^11.3.1
  table_calendar: ^3.1.2
  provider: ^6.1.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  flutter_datetime_picker: ^1.5.1
  age_calculator: ^1.0.0
  bottom_picker: ^2.8.0
  webview_flutter: ^4.8.0
  package_info_plus: ^8.0.0
  introduction_screen: ^3.1.14
  flame: ^1.18.0
  flame_forge2d: ^0.18.1
  google_mobile_ads: ^5.1.0
  app_tracking_transparency: ^2.0.5
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/images/games/
    - assets/images/games/catch/
    - assets/images/games/jump/
    - assets/images/games/jump/parallax/

  fonts:
    - family: TsunagiGothic
      fonts:
        - asset: assets/fonts/TsunagiGothic.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: #08bed5
  adaptive_icon_foreground: "assets/images/icon_adaptive_foreground.png"